/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'site-pages': SitePage;
    'announcement-banners': AnnouncementBanner;
    landings: Landing;
    'user-invites': UserInvite;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'site-pages': SitePagesSelect<false> | SitePagesSelect<true>;
    'announcement-banners': AnnouncementBannersSelect<false> | AnnouncementBannersSelect<true>;
    landings: LandingsSelect<false> | LandingsSelect<true>;
    'user-invites': UserInvitesSelect<false> | UserInvitesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Search and social metadata for code-owned public pages. This does not change page body copy or layout.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-pages".
 */
export interface SitePage {
  id: number;
  title: string;
  /**
   * Admin-only. Match a known code-owned page path, e.g. /, /about, /groups/birthdays. Landing pages use /c/* instead.
   */
  path: string;
  /**
   * Published in CMS means this metadata is approved. It is Live after deploy when the static public site rebuilds.
   */
  published?: boolean | null;
  seo: {
    /**
     * <title> and og:title for the code-owned page
     */
    metaTitle: string;
    metaDescription: string;
    robots?: ('index,follow' | 'noindex,follow') | null;
    /**
     * Root-relative path, e.g. /assets/photos/...
     */
    ogImage: string;
    /**
     * Defaults to og:image if empty
     */
    twitterImage?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Text-only top banner messages. Publish in CMS to approve; the public site shows the winning active banner after the next approved deploy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcement-banners".
 */
export interface AnnouncementBanner {
  id: number;
  /**
   * Internal label for editors. This is not shown on the public site.
   */
  title: string;
  /**
   * Higher priority wins when multiple banners are active. Matching priorities use the newest start date.
   */
  priority?: number | null;
  /**
   * Text-only banner message. Keep it short enough to scan in the moving top banner.
   */
  message: string;
  /**
   * Published in CMS means approved. It is Live after deploy when the static public site rebuilds.
   */
  published?: boolean | null;
  /**
   * Optional. Leave empty to make the banner eligible immediately after deploy.
   */
  startsAt?: string | null;
  /**
   * Optional. Leave empty for no scheduled end.
   */
  endsAt?: string | null;
  /**
   * Use all visitors unless this announcement is specific to a region or location page.
   */
  targetScope: 'global' | 'regions' | 'locations';
  /**
   * The banner is eligible only on pages associated with these regions.
   */
  targetRegions?:
    | {
        region: 'us' | 'europe';
        id?: string | null;
      }[]
    | null;
  /**
   * The banner is eligible only on these location pages.
   */
  targetLocations?:
    | {
        /**
         * Location slug
         */
        locationSlug: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional text link label. Example: Learn more.
   */
  linkLabel?: string | null;
  /**
   * Optional clean internal path or credential-free https URL.
   */
  linkUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Campaign and promotional pages rendered under /c/{slug}.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landings".
 */
export interface Landing {
  id: number;
  title: string;
  /**
   * URL segment: /c/{slug} (lowercase, hyphens only)
   */
  slug: string;
  /**
   * Layout guide inspired by existing Time Mission pages. Use Preview after saving to see it on Railway.
   */
  template: 'campaign' | 'paid_social_campaign' | 'group_event' | 'location_promo' | 'local_venue_city' | 'coming_soon';
  /**
   * When checked, this page is included in the public site build.
   */
  published?: boolean | null;
  /**
   * If off, page is still built but omitted from sitemap.xml.
   */
  includeInSitemap?: boolean | null;
  brief?: {
    sourceChannel?: ('paid_ad' | 'organic_social' | 'email' | 'local_search' | 'partner' | 'internal' | 'other') | null;
    sourceName?: string | null;
    sourceUrl?: string | null;
    sourcePromise?: string | null;
    visitorIntent?: string | null;
    successMetric?: string | null;
  };
  seo: {
    /**
     * <title> and og:title
     */
    metaTitle: string;
    metaDescription: string;
    robots?: ('index,follow' | 'noindex,follow') | null;
    /**
     * Optional full https URL on timemission.com; leave empty for default https://timemission.com/c/{slug}
     */
    canonicalOverride?: string | null;
    /**
     * Root-relative path, e.g. /assets/photos/...
     */
    ogImage: string;
    /**
     * Defaults to og:image if empty
     */
    twitterImage?: string | null;
  };
  content: {
    headline: string;
    subheadline?: string | null;
    bullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    primaryCtaLabel: string;
    ctaSurface: 'book_panel' | 'missions' | 'groups' | 'contact' | 'gift_cards' | 'external';
    /**
     * https://... when CTA surface is External
     */
    ctaExternalUrl?: string | null;
  };
  strategy?: {
    audience?: string | null;
    campaignGoal?: string | null;
    offerType?: string | null;
    locationOrCity?: string | null;
    eventType?: string | null;
    launchState?: ('open' | 'coming_soon') | null;
    proofAngle?: string | null;
    ctaIntent?: string | null;
  };
  paidSocial?: {
    sourcePromise?: string | null;
    frictionReducer?: string | null;
  };
  localVenue?: {
    cityProof?: string | null;
    venueConfidence?: string | null;
    openingNote?: string | null;
  };
  groupEvent?: {
    plannerReassurance?: string | null;
    groupSize?: string | null;
    logisticsNote?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Owner-only invites for CMS access. Creating an invite emails a password setup link.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-invites".
 */
export interface UserInvite {
  id: number;
  /**
   * The email address that will receive the CMS invite.
   */
  email: string;
  /**
   * Editors manage page content. Admins can also access admin-level CMS areas.
   */
  role: 'admin' | 'editor';
  status: 'pending' | 'sent' | 'failed';
  sentAt?: string | null;
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Only the CMS owner can assign roles. Editors manage landing content only.
   */
  role: 'admin' | 'editor';
  /**
   * Owner-granted permission to publish approved CMS changes to the public site. Roles alone do not grant deploy access.
   */
  canDeploy?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'site-pages';
        value: number | SitePage;
      } | null)
    | ({
        relationTo: 'landings';
        value: number | Landing;
      } | null)
    | ({
        relationTo: 'user-invites';
        value: number | UserInvite;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-pages_select".
 */
export interface SitePagesSelect<T extends boolean = true> {
  title?: T;
  path?: T;
  published?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        robots?: T;
        ogImage?: T;
        twitterImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "announcement-banners_select".
 */
export interface AnnouncementBannersSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  message?: T;
  published?: T;
  startsAt?: T;
  endsAt?: T;
  targetScope?: T;
  targetRegions?:
    | T
    | {
        region?: T;
        id?: T;
      };
  targetLocations?:
    | T
    | {
        locationSlug?: T;
        id?: T;
      };
  linkLabel?: T;
  linkUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landings_select".
 */
export interface LandingsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  template?: T;
  published?: T;
  includeInSitemap?: T;
  brief?:
    | T
    | {
        sourceChannel?: T;
        sourceName?: T;
        sourceUrl?: T;
        sourcePromise?: T;
        visitorIntent?: T;
        successMetric?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        robots?: T;
        canonicalOverride?: T;
        ogImage?: T;
        twitterImage?: T;
      };
  content?:
    | T
    | {
        headline?: T;
        subheadline?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        primaryCtaLabel?: T;
        ctaSurface?: T;
        ctaExternalUrl?: T;
      };
  strategy?:
    | T
    | {
        audience?: T;
        campaignGoal?: T;
        offerType?: T;
        locationOrCity?: T;
        eventType?: T;
        launchState?: T;
        proofAngle?: T;
        ctaIntent?: T;
      };
  paidSocial?:
    | T
    | {
        sourcePromise?: T;
        frictionReducer?: T;
      };
  localVenue?:
    | T
    | {
        cityProof?: T;
        venueConfidence?: T;
        openingNote?: T;
      };
  groupEvent?:
    | T
    | {
        plannerReassurance?: T;
        groupSize?: T;
        logisticsNote?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-invites_select".
 */
export interface UserInvitesSelect<T extends boolean = true> {
  email?: T;
  role?: T;
  status?: T;
  sentAt?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  canDeploy?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}
