/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'site-pages': SitePage;
    landings: Landing;
    'user-invites': UserInvite;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'site-pages': SitePagesSelect<false> | SitePagesSelect<true>;
    landings: LandingsSelect<false> | LandingsSelect<true>;
    'user-invites': UserInvitesSelect<false> | UserInvitesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * SEO metadata for static Astro pages. Match the canonical path exactly, such as /about.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-pages".
 */
export interface SitePage {
  id: number;
  title: string;
  /**
   * Existing page path, e.g. /, /about, /groups/birthdays.
   */
  path: string;
  /**
   * When checked, the Astro build can use this metadata for the matching existing page.
   */
  published?: boolean | null;
  seo: {
    /**
     * <title> and og:title for the existing page
     */
    metaTitle: string;
    metaDescription: string;
    robots?: ('index,follow' | 'noindex,follow') | null;
    /**
     * Root-relative path, e.g. /assets/photos/...
     */
    ogImage: string;
    /**
     * Defaults to og:image if empty
     */
    twitterImage?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Campaign and promotional pages rendered under /c/{slug}.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landings".
 */
export interface Landing {
  id: number;
  title: string;
  /**
   * URL segment: /c/{slug} (lowercase, hyphens only)
   */
  slug: string;
  /**
   * Layout guide inspired by existing Time Mission pages. Use Preview after saving to see it on Railway.
   */
  template: 'campaign' | 'group_event' | 'location_promo' | 'coming_soon';
  /**
   * When checked, this page is included in the public site build.
   */
  published?: boolean | null;
  /**
   * If off, page is still built but omitted from sitemap.xml.
   */
  includeInSitemap?: boolean | null;
  seo: {
    /**
     * <title> and og:title
     */
    metaTitle: string;
    metaDescription: string;
    robots?: ('index,follow' | 'noindex,follow') | null;
    /**
     * Optional full https URL on timemission.com; leave empty for default https://timemission.com/c/{slug}
     */
    canonicalOverride?: string | null;
    /**
     * Root-relative path, e.g. /assets/photos/...
     */
    ogImage: string;
    /**
     * Defaults to og:image if empty
     */
    twitterImage?: string | null;
  };
  content: {
    headline: string;
    subheadline?: string | null;
    bullets?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    primaryCtaLabel: string;
    ctaSurface: 'book_panel' | 'missions' | 'groups' | 'contact' | 'gift_cards' | 'external';
    /**
     * https://... when CTA surface is External
     */
    ctaExternalUrl?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Owner-only invites for CMS access. Creating an invite emails a password setup link.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-invites".
 */
export interface UserInvite {
  id: number;
  /**
   * The email address that will receive the CMS invite.
   */
  email: string;
  /**
   * Editors manage page content. Admins can also access admin-level CMS areas.
   */
  role: 'admin' | 'editor';
  status: 'pending' | 'sent' | 'failed';
  sentAt?: string | null;
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Only the CMS owner can assign roles. Editors manage landing content only.
   */
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'site-pages';
        value: number | SitePage;
      } | null)
    | ({
        relationTo: 'landings';
        value: number | Landing;
      } | null)
    | ({
        relationTo: 'user-invites';
        value: number | UserInvite;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-pages_select".
 */
export interface SitePagesSelect<T extends boolean = true> {
  title?: T;
  path?: T;
  published?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        robots?: T;
        ogImage?: T;
        twitterImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "landings_select".
 */
export interface LandingsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  template?: T;
  published?: T;
  includeInSitemap?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        robots?: T;
        canonicalOverride?: T;
        ogImage?: T;
        twitterImage?: T;
      };
  content?:
    | T
    | {
        headline?: T;
        subheadline?: T;
        bullets?:
          | T
          | {
              text?: T;
              id?: T;
            };
        primaryCtaLabel?: T;
        ctaSurface?: T;
        ctaExternalUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-invites_select".
 */
export interface UserInvitesSelect<T extends boolean = true> {
  email?: T;
  role?: T;
  status?: T;
  sentAt?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}